### ISSUE TITLE
Using Modem in Cluster environment

### ISSUE THREAD

**Issue by majutaca** [emilsedgh/modem#20] opened 2015-01-14 21:40 UTC
I ma failing to use modem with nodejs cluster, l get the following error

/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/lib/modem.js:176
                this.queue[0]['end_time'] = new Date();
                                          ^
TypeError: Cannot set property 'end_time' of undefined
    at EventEmitter.<anonymous> (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/lib/modem.js:176:43)
    at Array.forEach (native)
    at EventEmitter.modem.dataReceived (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/lib/modem.js:123:15)
    at SerialPort.EventEmitter.emit (events.js:95:17)
    at Object.module.exports.raw [as parser] (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/node_modules/serialport/parsers.js:8:13)
    at Object.SerialPort.options.dataCallback (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/node_modules/serialport/serialport.js:167:15)
    at SerialPortFactory.SerialPort._emitData (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/node_modules/serialport/serialport.js:349:20)
    at afterRead (/home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/node_modules/serialport/serialport.js:325:20)
    at /home/chris/SoftWyze/node-prjt/bhora-api/node_modules/modem/node_modules/serialport/serialport.js:341:9
    at Object.wrapper [as oncomplete] (fs.js:454:17)

This is what my bin/www looks like
var cluster = require('cluster');
var http = require('http');
var numCPUs = require('os').cpus().length;

var debug = require('debug')('bhora-api');
var app = require('../app');

if (cluster.isMaster) {
    // Fork workers.
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on('exit', function(worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
    });
} else {
    // Workers can share any TCP connection
    // In this case its a HTTP server
    app.set('port', process.env.PORT || 3000);

    var server = app.listen(app.get('port'), function() {
        debug('Express server listening on port ' + server.address().port);
    });
}

app.js is where l try to initialize the modem

**Comment by emilsedgh** [comment] 2015-01-14 21:42
This is a duplicate of #14 .

**Closed by emilsedgh** 2015-01-14 21:42 UTC
